#   Code developed by: g5fighter

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QAction, QMenu, QSystemTrayIcon

# Not autogenerated imports
import win32api, win32con, win32process, win32gui
from pycaw.pycaw import AudioUtilities
from PyQt5.QtCore import QTimer
import os.path
import json
import subprocess

# Global variables
spotifyPath = ""            # Spotify path
processpid = -1             # Spotify process pid
actual_song = ""            # Spotify Song being reproduced
is_muting = False           # Mute state of app
open_onStart = False        # Open Spotify on start muting (it will not work for Spotify installed via Windows Store)
hide_onStart = False        # Hide window on start muting to tray
ui = ""                     # UI element
datafilename = ".data"      # Filename of user data
hownd = ""                  #
isSpotifyMuted = False      # Updates de mute state of Spotify
isHided = False

# resource_path(relative_path)
#   gets a string "relative_path"
#   returns the path of the file
def resource_path(relative_path):
    if hasattr(sys, '_MEIPASS'):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)

# resource_path()
#   if process for "filename" exists
#       sets "spotifyPath" and "processpid"
def getSpotifyData():
    processes = win32process.EnumProcesses() 
    for pid in processes:
        try:
            handle = win32api.OpenProcess(win32con.PROCESS_ALL_ACCESS, False, pid)
            exe = win32process.GetModuleFileNameEx(handle, 0)
            if "spotify.exe" in exe.lower():
                global spotifyPath
                spotifyPath = exe
                global processpid
                processpid = pid
                return True
        except:
            pass
    return False

# resource_path(hwnd, ctx)
#   if process is equal to "processpid"
#       sets "actual_song" to title window name
def winEnumHandler(hwnd, ctx):
    if win32gui.IsWindowVisible(hwnd):
        if(win32process.GetWindowThreadProcessId(hwnd)[1] == processpid):
            global actual_song
            actual_song = win32gui.GetWindowText(hwnd)
            global hownd # no setear si existe
            hownd = hwnd
            return

# getWindowName()
#   if "hownd" is ""
#       gets all windows and calls winEnumHandler()
#   else
#       gets the name of the window by "hownd"
def getWindowName():
    if hownd == "":
        win32gui.EnumWindows(winEnumHandler, None)
    else:
        winEnumHandler(hownd, None)

# isAdvertisement()
#   returns True if the app name is an Advertisement
def isAdvertisement():
    return "Advertisement" in actual_song or "Spotify" in actual_song

# getWindowName()
#   if "is_muting" is True checks if is an ad and calls setMute()
def mute_app():
    if is_muting:
        getWindowName()
        if not isHided:
            ui.update_song(actual_song)
        if isAdvertisement():
            setMute(1)
        else:
            setMute(0)

# setMute(state)
#   gets an int "state"
#       searches Spotify service and mutes or unmates it
def setMute(state):
    global isSpotifyMuted
    if (state == 1) or (state == 0 and isSpotifyMuted): # and not isSpotifyMuted
        sessions = AudioUtilities.GetAllSessions()
        for session in sessions:
            process = session.Process
            if process!=None:
                if "spotify.exe" in session.Process.name().lower():
                    volume = session.SimpleAudioVolume
                    volume.SetMute(state, None)
                    isSpotifyMuted = state==1

# initialConf()
#   if file "datafilename" exsits gets the info form the file and set global variables
#   else creates that file and storesthe actual config
def initialConf():
    if os.path.isfile(datafilename):
        with open(datafilename) as f:
            data = json.load(f)
        global spotifyPath
        spotifyPath = data['SpotifyPath']
        global open_onStart
        open_onStart = bool(data['OpenStart'])
        global hide_onStart
        hide_onStart = bool(data['HideStart'])
    else:
        data = {}
        data['SpotifyPath']= spotifyPath
        data['OpenStart']=open_onStart
        data['HideStart']=hide_onStart
        with open(datafilename, 'w') as outfile:
            json.dump(data, outfile, indent=2)
    ui.update_checkBox()

# writeInJson(tag, value)
#   gets a string "tag" and a var "value"
#   it stores in the json the value in its tag
def writeInJson(tag, value):
    with open(datafilename, 'r+') as f:
        data = json.load(f)
        data[tag] = value
        f.seek(0)
        json.dump(data, f, indent=2)
        f.truncate()

# Auto-generated Class but with some modifications
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(416, 193)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(416, 193))
        MainWindow.setMaximumSize(QtCore.QSize(416, 193))
        MainWindow.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("iconadmuted.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off) #edited to recognize icon with PyInstaller
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 449, 171))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TExt = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TExt.sizePolicy().hasHeightForWidth())
        self.TExt.setSizePolicy(sizePolicy)
        self.TExt.setMinimumSize(QtCore.QSize(0, 20))
        self.TExt.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.TExt.setFont(font)
        self.TExt.setAutoFillBackground(False)
        self.TExt.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.TExt.setObjectName("TExt")
        self.verticalLayout.addWidget(self.TExt)
        self.MuteButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MuteButton.sizePolicy().hasHeightForWidth())
        self.MuteButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.MuteButton.setFont(font)
        self.MuteButton.setObjectName("MuteButton")
        self.verticalLayout.addWidget(self.MuteButton)
        self.OpenSpotifyCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.OpenSpotifyCheck.setFont(font)
        self.OpenSpotifyCheck.setObjectName("OpenSpotifyCheck")
        self.verticalLayout.addWidget(self.OpenSpotifyCheck)
        self.HideAppCheck = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.HideAppCheck.setFont(font)
        self.HideAppCheck.setObjectName("HideAppCheck")
        self.verticalLayout.addWidget(self.HideAppCheck)
        self.PlayingNowLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.PlayingNowLabel.sizePolicy().hasHeightForWidth())
        self.PlayingNowLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.PlayingNowLabel.setFont(font)
        self.PlayingNowLabel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.PlayingNowLabel.setObjectName("PlayingNowLabel")
        self.verticalLayout.addWidget(self.PlayingNowLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setEnabled(True)
        self.statusbar.setToolTip("")
        self.statusbar.setStatusTip("")
        self.statusbar.setAccessibleName("")
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AdMuted - An spotify ad silencer"))
        self.TExt.setText(_translate("MainWindow", "Start enjoying and no more adSuffering"))
        self.MuteButton.setText(_translate("MainWindow", "Start Muting"))
        self.OpenSpotifyCheck.setText(_translate("MainWindow", "Open Spotify on Start Muting"))
        self.HideAppCheck.setText(_translate("MainWindow", "Hide app on Start Muting"))
        self.PlayingNowLabel.setText(_translate("MainWindow", "Playing now:"))

        #MI CÓDIGO
        self.MuteButton.clicked.connect(self.muteButton)
        self.OpenSpotifyCheck.clicked.connect(self.open_at_start)
        self.HideAppCheck.clicked.connect(self.hide_at_start)

    ##### Custom functions for the UI

    # open_at_start()
    #   edits "open_onStart" and write it on the json
    def open_at_start(self):
        global open_onStart
        open_onStart = not open_onStart
        writeInJson('OpenStart', open_onStart)

    # hide_at_start()
    #   edits "hide_onStart" and write it on the json       
    def hide_at_start(self):
        global hide_onStart
        hide_onStart = not hide_onStart
        writeInJson('HideStart', hide_onStart)

    # showWindow()
    #   shows the window and hides the Tray icon    
    def showWindow(self):
        MainWindow.show()   
        self.tray.hide()  
        global isHided
        isHided = False 

    # convertInTray()
    #   Creates tray and hide the main window  
    def convertInTray(self):
        MainWindow.hide()
        global isHided
        isHided = True

        # Create the tray
        self.tray = QSystemTrayIcon()
        self.tray.setIcon(QtGui.QIcon(resource_path("iconadmuted.png")))
        self.tray.show()

        # Create the menu
        self.menu = QMenu()

        self.action1 = QAction("Return")
        self.action1.triggered.connect(self.showWindow)
        self.menu.addAction(self.action1)

        self.quit = QAction("Quit")
        self.quit.triggered.connect(app.quit)
        self.menu.addAction(self.quit)
        ##
        self.tray.setContextMenu(self.menu)
 
    # muteButton()
    #   changes muting state 
    def muteButton(self):
        global is_muting
        if not is_muting:
            if processpid==-1:
                if open_onStart:
                    try:
                        subprocess.call([spotifyPath])
                        getSpotifyData()
                        is_muting = not is_muting
                        self.MuteButton.setText("Is Muting")
                    except:
                        self.update_song("[Error]: Cannot open Spotify please do it manually")
                        return
                else:
                    self.PlayingNowLabel.setText("[Error]: Spotify is not running, open it and try again")  
            else:
                    is_muting = not is_muting
                    self.MuteButton.setText("Is Muting")
            if hide_onStart:
                self.convertInTray()
        else:
            is_muting = not is_muting
            self.MuteButton.setText("Start Muting")   
            ui.update_song("")         

    # update_checkBox()
    #   updates chackbox gui state     
    def update_checkBox(self):
        self.OpenSpotifyCheck.setChecked(open_onStart)
        self.HideAppCheck.setChecked(hide_onStart)

    # update_song(song)
    #   get a string "song"
    #   changes playing song label     
    def update_song(self, song):
        self.PlayingNowLabel.setText("Playing now: "+song)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    ## Custom functions ##
    getSpotifyData()
    initialConf()
    timer = QTimer()
    timer.timeout.connect(mute_app)
    timer.start(1000)
    ## Custom functions ##
    sys.exit(app.exec_())